# Granular feature permissions used by the developer panel.
FEATURES = [
    ("automation.monitor", "مراقبة الرسائل الواردة"),
    ("automation.edits", "مراقبة تعديل الرسائل"),
    ("automation.deleted_log", "سجل الرسائل المحذوفة"),
    ("automation.save_messages", "حفظ الرسائل"),
    ("automation.save_media", "حفظ الوسائط"),
    ("automation.mute", "كتم مستخدم"),
    ("automation.unmute", "إلغاء الكتم"),
    ("automation.muted_list", "عرض المكتومين"),
    ("automation.mute_by_id", "الكتم بالـ ID"),
    ("automation.mute_by_username", "الكتم بالـ Username"),
    ("automation.reply_commands", "أوامر الكتم بالرد"),
    ("automation.exceptions", "استثناءات الأشخاص"),
    ("automation.person_permissions", "صلاحيات الأشخاص"),
    ("automation.message_filters", "فلاتر نوع الرسائل"),
    ("automation.auto_replies", "الردود التلقائية"),
    ("automation.rules", "القواعد والأتمتة"),
    ("automation.scheduled", "المهام المجدولة"),
    ("private.people", "عرض الأشخاص في الخاص"),
    ("private.import", "استيراد الرسائل القديمة"),
    ("private.search", "البحث في المحادثات"),
    ("private.open_chat", "فتح سجل محادثة"),
    ("private.save_chat", "حفظ محادثة"),
    ("private.multi_select", "تحديد محادثات متعددة"),
    ("private.select_all", "تحديد الكل"),
    ("private.exclude", "استثناء محادثات"),
    ("private.archive", "أرشفة وتنظيم المحادثات"),
    ("private.stats", "إحصائيات الشخص"),
    ("private.own_messages", "تتبع الرسائل الصادرة"),
    ("private.other_messages", "تتبع الرسائل الواردة"),
    ("storage.text", "حفظ النصوص"),
    ("storage.images", "حفظ الصور"),
    ("storage.videos", "حفظ الفيديوهات"),
    ("storage.files", "حفظ الملفات"),
    ("storage.audio", "حفظ الصوتيات"),
    ("storage.stickers", "حفظ الملصقات"),
    ("storage.gifs", "حفظ GIF"),
    ("storage.links", "حفظ الروابط"),
    ("storage.forwarded", "حفظ الرسائل المحولة"),
    ("storage.search", "البحث في التخزين"),
    ("storage.date_search", "البحث بالتاريخ"),
    ("storage.browse", "تصفح سجل المحادثات"),
    ("storage.export", "تصدير المحادثة"),
    ("storage.backup", "النسخ الاحتياطي"),
    ("storage.restore", "استرجاع النسخة الاحتياطية"),
    ("important.add", "حفظ رسالة مهمة"),
    ("important.search", "البحث عن رسالة للحفظ"),
    ("important.confirm", "تأكيد حفظ الرسالة"),
    ("important.cancel", "إلغاء حفظ الرسالة"),
    ("important.list", "عرض الرسائل المهمة"),
    ("important.search_saved", "البحث في الرسائل المهمة"),
    ("stats.people", "إحصائيات الأشخاص"),
    ("stats.messages", "إحصائيات الرسائل"),
    ("stats.media", "إحصائيات الوسائط"),
    ("stats.links", "إحصائيات الروابط"),
    ("stats.storage", "إحصائيات التخزين"),
    ("stats.today", "إحصائيات اليوم"),
    ("stats.week", "إحصائيات الأسبوع"),
    ("stats.month", "إحصائيات الشهر"),
    ("stats.all", "الإحصائيات الكلية"),
    ("broadcast.create", "إنشاء إذاعة"),
    ("broadcast.preview", "معاينة الإذاعة"),
    ("broadcast.send", "إرسال الإذاعة"),
    ("broadcast.exclude", "استثناء شخص من الإذاعة"),
    ("broadcast.remove_exclusion", "إزالة استثناء الإذاعة"),
    ("broadcast.exclusions", "إدارة المستثنين"),
    ("broadcast.schedule", "جدولة الإذاعة"),
    ("broadcast.cancel_schedule", "إلغاء الإذاعة المجدولة"),
    ("broadcast.log", "سجل الإذاعات"),
    ("broadcast.stats", "إحصائيات الإذاعة"),
    ("protection.media_scan", "فحص الوسائط"),
    ("protection.violation_alerts", "تنبيهات المحتوى المخالف"),
    ("protection.log", "سجل الحماية"),
    ("protection.settings", "إعدادات الحماية"),
    ("protection.ownership", "الحماية من نقل الملكية"),
    ("protection.ownership_enable", "تفعيل حماية نقل الملكية"),
    ("protection.ownership_disable", "إيقاف حماية نقل الملكية"),
    ("protection.operations", "سجل عمليات الحماية"),
    ("log.operations", "سجل العمليات"),
    ("log.search", "البحث في السجل"),
    ("log.filters", "فلترة السجل"),
    ("notifications.deleted", "إشعارات الرسائل المحذوفة"),
    ("notifications.edited", "إشعارات التعديل"),
    ("notifications.media", "إشعارات الوسائط"),
    ("notifications.new_contact", "إشعارات المستخدمين الجدد"),
    ("notifications.links", "إشعارات الروابط"),
    ("notifications.settings", "إعدادات الإشعارات"),
    ("settings.general", "الإعدادات العامة"),
    ("settings.backup", "إعدادات النسخ الاحتياطي"),
    ("settings.storage", "إعدادات التخزين"),
    ("settings.notifications", "إعدادات التنبيهات"),
    ("settings.protection", "إعدادات الحماية"),
    ("settings.rules", "إعدادات القواعد"),
    ("ai.settings", "إعدادات الذكاء الاصطناعي"),
    ("ai.logs", "سجل الذكاء الاصطناعي"),
    ("ai.toggle", "تشغيل وإيقاف الذكاء الاصطناعي"),
    ("ai.trigger", "تغيير اسم الذكاء الاصطناعي"),
]
FEATURE_LABELS = dict(FEATURES)
FEATURE_KEYS = [k for k, _ in FEATURES]

def category_for(key):
    return key.split('.', 1)[0]
